### ISSUE TITLE
undefined reference to `IntArray_t'

### ISSUE THREAD

**Issue by LyttleG** [sagartewari01/ooc#1]
Hello,

Nice work you did!
BTW, there is an issue when compiling source code within 'article-2-methods' package using CodeBlocks and GCC version version 5.1.0 (tdm-1) under Windows 10 (using 32 bits compiler)

||=== Build: Debug in OOPInC (compiler: GNU GCC Compiler) ===|
obj\Debug\main.o||In function `main':|
..\main.c|7|undefined reference to `IntArray_t'|
||error: ld returned 1 exit status|
||=== Build failed: 2 error(s), 0 warning(s) (0 minute(s), 1 second(s)) ===|

**Comment by sagartewari01** [comment]
@LyttleG It was because of an untracked file (IntArray.c). A `git pull origin article-2-methods` should fix this problem.

**Comment by LyttleG** [comment]
Thanks for the update Sagar!
